name: Release

on:
  workflow_dispatch:
    branch:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.PA_TOKEN }}

      - name: Set release information
        id: set-release-info
        run: |
          if [ -z "${{ steps.changelog.outputs.clean_changelog }}" ]; then
            echo "No changelog found. Using GitHub ref for release details."
            echo "tag_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
            echo "release_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
            echo "body=No changelog available. This release is based on commit ${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "Changelog found. Using generated changelog for release."
            echo "tag_name=${{ steps.changelog.outputs.tag }}" >> $GITHUB_ENV
            echo "release_name=${{ steps.changelog.outputs.tag }}" >> $GITHUB_ENV
            echo "body=${{ steps.changelog.outputs.clean_changelog }}" >> $GITHUB_ENV
          fi

      - name: Create realease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: ${{ env.release_name }}
          body: ${{ env.body }}
